#!/bin/bash

git clone https://github.com/quinngroup/ornet
cd ornet
pip install -r requirements.txt
pip install .
echo $(pwd)
mkdir -p ../outputs ../outputs/distances ../outputs/downsampled ../outputs/eigendata \
    ../outputs/intermediates  ../outputs/normalized  ../outputs/plots  \
    ../outputs/singles ../outputs/patial-tracking
